### ISSUE TITLE
Solutions

### ISSUE THREAD

**Issue by seanmarcia** [angularjs-foundation/video-exercises#4]
Are the authors solutions to hands on exercises available somewhere? I don't see them in the videos or in the repo and it would be nice to see how closely what I am doing matches up to a "canonical" solution. I am interested in not developing any bad practices as I learn.

**Comment by simpulton** [comment]
Good question! Checkout `master` from the [angularjs-foundation/video-app](https://github.com/angularjs-foundation/video-app) repo to see the completed application.
